export const CONTRIBUTORS = [
  "phono's",
  "Goopsky's",
  "Fahr's",
  "Dwarf's Foundry",
  "Tupper's",
  "Schorty's",
  "nerdkusi's",
  "KrzysD's",
  "Geo's",
  "Brodo's",
  "gigajum's",
  "Tom's",
  "SickHippie's",
  "TheTostu's",
  "Cyberboss's",
  "THE FACTORY's",
  "George's",
  "gcho's"
  'Autotorio Approved™',
];
