export const CONTRIBUTORS = [
  "phono's",
  "Goopsky's",
  'Fahr',
  "Dwarf's Foundry",
  "Tupper's",
  "Schorty's",
  "nerdkusi's",
  "KrzysD's",
  "Geo's",
  "Brodo's",
  "gigajum's",
  "Tom's",
  'SickHippie',
  "TheTostu's",
  'Cyberboss',
  'THE FACTORY',
  'Autotorio Approved™',
];
